version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - misspell
    - revive
    - gocyclo
    - unused

  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - (*os.File).Close
        - os.Remove
    gocyclo:
      min-complexity: 15
    revive:
      rules:
        - name: exported
          disabled: true

formatters:
  enable:
    - gofmt

issues:
  max-same-issues: 0
