services:
  goscii-go:
    build:
      context: .
      dockerfile: docker/go.Dockerfile
    image: ghcr.io/ashbuk/goscii-go:latest
    stdin_open: true
    tty: true
    volumes:
      - ~/.local/share/goscii:/home/goscii/.local/share/goscii
